from __future__ import annotations

from datetime import date
from pathlib import Path

from mixedsig2cad.layout import SchematicLayout, build_kicad_layout, deterministic_uuid
from mixedsig2cad.spec import CircuitSpec

SYMBOL_LIBRARY_PATH = Path(__file__).resolve().parents[1] / "assets" / "examples.kicad_sym"


def _symbol_property(name: str, value: str, x: float, y: float, *, hidden: bool = False) -> list[str]:
    effects = "(effects (font (size 1.27 1.27)) hide)" if hidden else "(effects (font (size 1.27 1.27)))"
    return [
        f'    (property "{name}" "{value}" (at {x} {y} 0)',
        f"      {effects}",
        "    )",
    ]


def _wire(x1: float, y1: float, x2: float, y2: float, seed: str) -> list[str]:
    return [
        f"  (wire (pts (xy {x1:.2f} {y1:.2f}) (xy {x2:.2f} {y2:.2f}))",
        "    (stroke (width 0) (type solid) (color 0 0 0 0))",
        f"    (uuid {deterministic_uuid(seed)})",
        "  )",
    ]


def _label(text: str, x: float, y: float, seed: str) -> list[str]:
    return [
        f'  (label "{text}" (at {x:.2f} {y:.2f} 0)',
        "    (effects (font (size 1.27 1.27)) (justify left bottom))",
        f"    (uuid {deterministic_uuid(seed)})",
        "  )",
    ]


def _junction(x: float, y: float) -> str:
    return f"  (junction (at {x:.2f} {y:.2f}) (diameter 1.016) (color 0 0 0 0))"


def _extract_symbol_block(symbol_name: str) -> str:
    text = SYMBOL_LIBRARY_PATH.read_text(encoding="utf-8")
    needle = f'(symbol "{symbol_name}"'
    start = text.find(needle)
    if start < 0:
        raise RuntimeError(f"symbol '{symbol_name}' not found in {SYMBOL_LIBRARY_PATH}")
    depth = 0
    end = -1
    for idx in range(start, len(text)):
        ch = text[idx]
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
            if depth == 0:
                end = idx + 1
                break
    if end < 0:
        raise RuntimeError(f"failed to parse symbol block '{symbol_name}' in {SYMBOL_LIBRARY_PATH}")
    return text[start:end]


def _lib_symbols_block(layout: SchematicLayout) -> list[str]:
    lines = ["  (lib_symbols"]
    symbol_names = sorted({symbol.lib_id for symbol in layout.symbols})
    for symbol_name in symbol_names:
        block = _extract_symbol_block(symbol_name)
        for row in block.splitlines():
            lines.append(f"    {row}")
    lines.append("  )")
    return lines


def export_kicad_schematic(spec: CircuitSpec) -> str:
    return render_kicad_schematic(build_kicad_layout(spec))


def render_kicad_schematic(layout: SchematicLayout) -> str:
    schematic_uuid = deterministic_uuid(f"sch:{layout.name}")
    lines: list[str] = [
        "(kicad_sch",
        "  (version 20231120)",
        '  (generator "mixedsig2cad")',
        f"  (uuid {schematic_uuid})",
        '  (paper "A4")',
        "  (title_block",
        f'    (title "{layout.name}")',
        f'    (date "{date.today().isoformat()}")',
        '    (comment 1 "Generated by mixedsig2cad")',
        "  )",
    ]
    lines.extend(_lib_symbols_block(layout))

    for symbol in layout.symbols:
        placement = symbol.placement
        lines.extend(
            [
                f'  (symbol (lib_id "{symbol.lib_id}") (at {placement.x:.2f} {placement.y:.2f} {placement.angle}) (unit 1)',
                "    (in_bom yes) (on_board yes)",
                f"    (uuid {symbol.uuid})",
                *_symbol_property("Reference", symbol.ref, placement.x, placement.y - 3.81, hidden=symbol.hidden_reference),
                *_symbol_property("Value", symbol.value, placement.x, placement.y + 3.81),
                *_symbol_property("Footprint", "", 0, 0, hidden=True),
                *_symbol_property("Datasheet", "", 0, 0, hidden=True),
                "  )",
            ]
        )

    for label in layout.labels:
        lines.extend(_label(label.text, label.x, label.y, label.uuid_seed))

    for wire in layout.wires:
        lines.extend(_wire(wire.x1, wire.y1, wire.x2, wire.y2, wire.uuid_seed))

    for junction in layout.junctions:
        lines.append(_junction(junction.x, junction.y))

    lines.extend(
        [
            "  (sheet_instances",
            '    (path "/" (page "1"))',
            "  )",
            "  (symbol_instances",
        ]
    )

    for symbol in layout.symbols:
        lines.append(
            f'    (path "/{symbol.uuid}" (reference "{symbol.ref}") (unit 1) (value "{symbol.value}") (footprint ""))'
        )

    lines.extend(["  )", ")"])
    return "\n".join(lines) + "\n"
