from __future__ import annotations

import uuid
from collections import defaultdict
from datetime import date
from typing import DefaultDict

from mixedsig2cad.spec import CircuitSpec


SYMBOL_BY_KIND = {
    "R": "Device:R",
    "C": "Device:C",
    "L": "Device:L",
    "V": "pspice:VSOURCE",
    "I": "pspice:ISOURCE",
    "D": "Device:D",
    "Q": "Device:Q_NPN_BCE",
    "M": "Device:Q_PMOS_GSD",
    "X": "Amplifier_Operational:LM358",
}


def _uuid(seed: str) -> str:
    return str(uuid.uuid5(uuid.NAMESPACE_URL, seed))


def _symbol_property(name: str, value: str, x: float, y: float, *, hidden: bool = False) -> list[str]:
    """Emit KiCad symbol property syntax compatible with KiCad 8 parser.

    Hidden properties must express `hide` inside the `effects` stanza, not as a
    standalone property child node.
    """
    effects = "(effects (font (size 1.27 1.27)) hide)" if hidden else "(effects (font (size 1.27 1.27)))"
    return [
        f'    (property "{name}" "{value}" (at {x} {y} 0)',
        f"      {effects}",
        "    )",
    ]


def _symbol_for_component(kind: str, value: str, model: str | None) -> str:
    if kind != "M":
        return SYMBOL_BY_KIND.get(kind, "Device:R")
    hint = f"{value} {model or ''}".lower()
    if "nm" in hint or "nmos" in hint:
        return "Device:Q_NMOS_GSD"
    return "Device:Q_PMOS_GSD"


def _wire(x1: float, y1: float, x2: float, y2: float, seed: str) -> list[str]:
    return [
        f"  (wire (pts (xy {x1:.2f} {y1:.2f}) (xy {x2:.2f} {y2:.2f}))",
        "    (stroke (width 0) (type solid) (color 0 0 0 0))",
        f"    (uuid {_uuid(seed)})",
        "  )",
    ]


def _label(net: str, x: float, y: float, seed: str) -> list[str]:
    return [
        f'  (label "{net}" (at {x:.2f} {y:.2f} 0)',
        "    (effects (font (size 1.27 1.27)) (justify left bottom))",
        f"    (uuid {_uuid(seed)})",
        "  )",
    ]


def _junction(x: float, y: float) -> str:
    return f"  (junction (at {x:.2f} {y:.2f}) (diameter 1.016) (color 0 0 0 0))"


def _pin_anchor(pos: tuple[float, float], pin_index: int, pin_count: int) -> tuple[float, float]:
    x, y = pos
    spread = max(1, pin_count - 1)
    x0 = x - 6.0
    step = 12.0 / spread
    px = x0 + (pin_index * step)
    py = y - 6.0 if pin_index < (pin_count + 1) // 2 else y + 6.0
    return (px, py)


def _orthogonal_wire(
    p1: tuple[float, float],
    p2: tuple[float, float],
    seed: str,
) -> list[str]:
    x1, y1 = p1
    x2, y2 = p2
    if y1 == y2 or x1 == x2:
        return _wire(x1, y1, x2, y2, seed)
    mid_x = round((x1 + x2) / 2.0, 2)
    lines: list[str] = []
    lines.extend(_wire(x1, y1, mid_x, y1, f"{seed}:a"))
    lines.extend(_wire(mid_x, y1, mid_x, y2, f"{seed}:b"))
    lines.extend(_wire(mid_x, y2, x2, y2, f"{seed}:c"))
    lines.append(_junction(mid_x, y1))
    lines.append(_junction(mid_x, y2))
    return lines


def _net_map_lines(
    spec: CircuitSpec,
    pin_positions: DefaultDict[str, list[tuple[float, float]]],
) -> list[str]:
    if not pin_positions:
        return []

    nets = sorted(pin_positions.keys(), key=lambda n: (n != "0", n))
    lines: list[str] = []
    for net_idx, net in enumerate(nets):
        points = pin_positions[net]
        if not points:
            continue

        label_x = min(p[0] for p in points) - 6.0
        label_y = min(p[1] for p in points) - 1.5 - (net_idx % 2) * 1.5
        lines.extend(_label(net, label_x, label_y, f"label:{spec.name}:{net}"))

        if len(points) == 1:
            continue

        if len(points) == 2:
            lines.extend(_orthogonal_wire(points[0], points[1], f"net2:{spec.name}:{net}"))
            continue

        y_trunk = round(sum(p[1] for p in points) / len(points) + 6.0, 2)
        x_min = min(p[0] for p in points) - 1.0
        x_max = max(p[0] for p in points) + 1.0
        lines.extend(_wire(x_min, y_trunk, x_max, y_trunk, f"trunk:{spec.name}:{net}"))
        for point_idx, (px, py) in enumerate(points, start=1):
            lines.extend(_wire(px, py, px, y_trunk, f"stub:{spec.name}:{net}:{point_idx}"))
            lines.append(_junction(px, y_trunk))
    return lines


def export_kicad_schematic(spec: CircuitSpec) -> str:
    schematic_uuid = _uuid(f"sch:{spec.name}")
    lines: list[str] = [
        "(kicad_sch",
        "  (version 20231120)",
        '  (generator "mixedsig2cad")',
        f"  (uuid {schematic_uuid})",
        '  (paper "A4")',
        "  (title_block",
        f'    (title "{spec.name}")',
        f'    (date "{date.today().isoformat()}")',
        '    (comment 1 "Generated by mixedsig2cad")',
        "  )",
        "  (lib_symbols)",
    ]

    base_x = 50
    y = 50
    comp_positions: dict[str, tuple[float, float]] = {}
    pin_positions: DefaultDict[str, list[tuple[float, float]]] = defaultdict(list)
    for idx, comp in enumerate(spec.components, start=1):
        symbol_uuid = _uuid(f"sym:{spec.name}:{comp.ref}")
        lib_id = _symbol_for_component(comp.kind, comp.value, comp.model)
        x = base_x + (idx - 1) % 4 * 35
        if idx > 1 and (idx - 1) % 4 == 0:
            y += 30
        comp_positions[comp.ref] = (float(x), float(y))
        for pin_index, net in enumerate(comp.nodes):
            pin_positions[net].append(_pin_anchor(comp_positions[comp.ref], pin_index, len(comp.nodes)))
        lines.extend(
            [
                f"  (symbol (lib_id \"{lib_id}\") (at {x} {y} 0) (unit 1)",
                "    (in_bom yes) (on_board yes)",
                f"    (uuid {symbol_uuid})",
                *_symbol_property("Reference", comp.ref, x, y - 3.81),
                *_symbol_property("Value", comp.value, x, y + 3.81),
                *_symbol_property("Footprint", "", 0, 0, hidden=True),
                *_symbol_property("Datasheet", "", 0, 0, hidden=True),
                "  )",
            ]
        )

    lines.extend(_net_map_lines(spec, pin_positions))

    lines.extend(
        [
            "  (sheet_instances",
            '    (path "/" (page "1"))',
            "  )",
            "  (symbol_instances",
        ]
    )

    for comp in spec.components:
        symbol_uuid = _uuid(f"sym:{spec.name}:{comp.ref}")
        lines.append(
            f'    (path "/{symbol_uuid}" (reference "{comp.ref}") (unit 1) (value "{comp.value}") (footprint ""))'
        )

    lines.extend(["  )", ")"])
    return "\n".join(lines) + "\n"
