from __future__ import annotations

from dataclasses import dataclass

from mixedsig2cad.compiled import compile_schematic
from mixedsig2cad.design import ExampleDesign, circuit_of
from mixedsig2cad.intent import build_schematic_intent
from mixedsig2cad.layout_compiler import compile_design
from mixedsig2cad.models import CompiledSchematic, PlacedShape, Point, TextPlacement
from mixedsig2cad.projections.kicad import project_geometry_to_kicad
from mixedsig2cad.spec import CircuitSpec


SCALE = 0.1


@dataclass(frozen=True, slots=True)
class ReportSections:
    circuitikz: str
    literal_tikz: str
    summary: str
    starter_notes: str


def export_circuitikz(spec: ExampleDesign | CircuitSpec) -> str:
    geometry = _compiled_geometry(spec)
    return render_circuitikz(geometry)


def export_literal_tikz(spec: ExampleDesign | CircuitSpec) -> str:
    geometry = _compiled_geometry(spec)
    return render_literal_tikz(geometry)


def export_example_report_tex(spec: ExampleDesign | CircuitSpec) -> str:
    geometry = _compiled_geometry(spec)
    sections = _report_sections(spec, geometry)
    return _standalone_document(geometry.name, sections)


def export_examples_master_report(specs: list[ExampleDesign | CircuitSpec]) -> str:
    lines = [
        r"\documentclass[11pt]{article}",
        r"\usepackage[margin=1in]{geometry}",
        r"\usepackage[T1]{fontenc}",
        r"\usepackage{tikz}",
        r"\usepackage[american]{circuitikz}",
        r"\usepackage{longtable}",
        r"\usepackage{hyperref}",
        r"\title{mixedsig2cad Example Reports}",
        r"\author{Generated by mixedsig2cad}",
        r"\date{\today}",
        r"\begin{document}",
        r"\maketitle",
        r"\tableofcontents",
    ]
    for spec in specs:
        circuit_spec = circuit_of(spec)
        geometry = _compiled_geometry(spec)
        sections = _report_sections(spec, geometry)
        lines.extend(
            [
                "",
                rf"\section{{{_latex_escape(circuit_spec.name)}}}",
                r"\subsection{Readable Circuit}",
                sections.circuitikz,
                r"\subsection{Literal KiCad Reference}",
                sections.literal_tikz,
                r"\subsection{Reference Summary}",
                sections.summary,
                r"\subsection{Design Notes}",
                sections.starter_notes,
                r"\clearpage",
            ]
        )
    lines.append(r"\end{document}")
    return "\n".join(lines) + "\n"


def render_circuitikz(geometry: CompiledSchematic) -> str:
    lines = [
        r"\begin{circuitikz}[american voltages, scale=1, transform shape]",
    ]
    lines.extend(_render_circuitikz_shapes(geometry))
    lines.extend(_render_circuitikz_wires(geometry))
    lines.extend(_render_circuitikz_labels(geometry))
    lines.append(r"\end{circuitikz}")
    return "\n".join(lines)


def render_literal_tikz(geometry: CompiledSchematic) -> str:
    projection = project_geometry_to_kicad(geometry)
    lines = [
        r"\begin{tikzpicture}[x=0.1cm,y=-0.1cm,line cap=round,line join=round]",
    ]
    for wire in projection.wires:
        lines.append(
            rf"  \draw ({wire.x1:.2f},{wire.y1:.2f}) -- ({wire.x2:.2f},{wire.y2:.2f});"
        )
    for junction in projection.junctions:
        lines.append(rf"  \fill ({junction.x:.2f},{junction.y:.2f}) circle (1.2pt);")
    for symbol in geometry.shapes:
        lines.extend(_render_literal_shape(symbol))
    for text in geometry.labels:
        rendered = _render_literal_text(text)
        if rendered:
            lines.append(rendered)
    lines.append(r"\end{tikzpicture}")
    return "\n".join(lines)


def _compiled_geometry(spec: ExampleDesign | CircuitSpec) -> CompiledSchematic:
    if isinstance(spec, ExampleDesign):
        return compile_design(spec)
    intent = build_schematic_intent(circuit_of(spec))
    return compile_schematic(intent)


def _report_sections(spec: ExampleDesign | CircuitSpec, geometry: CompiledSchematic) -> ReportSections:
    return ReportSections(
        circuitikz=render_circuitikz(geometry),
        literal_tikz=render_literal_tikz(geometry),
        summary=_reference_section(circuit_of(spec)),
        starter_notes=_starter_notes(circuit_of(spec)),
    )


def _standalone_document(name: str, sections: ReportSections) -> str:
    escaped_name = _latex_escape(name)
    lines = [
        r"\documentclass[11pt]{article}",
        r"\usepackage[margin=1in]{geometry}",
        r"\usepackage[T1]{fontenc}",
        r"\usepackage{tikz}",
        r"\usepackage[american]{circuitikz}",
        r"\usepackage{longtable}",
        r"\usepackage{hyperref}",
        r"\title{" + escaped_name + r"}",
        r"\author{Generated by mixedsig2cad}",
        r"\date{\today}",
        r"\begin{document}",
        r"\maketitle",
        r"\section{Readable Circuit}",
        sections.circuitikz,
        r"\section{Literal KiCad Reference}",
        sections.literal_tikz,
        r"\section{Reference Summary}",
        sections.summary,
        r"\section{Design Notes}",
        sections.starter_notes,
        r"\end{document}",
    ]
    return "\n".join(lines) + "\n"


def _render_circuitikz_shapes(geometry: CompiledSchematic) -> list[str]:
    lines: list[str] = []
    for shape in geometry.shapes:
        if shape.shape == "resistor":
            lines.append(_two_terminal(shape, "R"))
        elif shape.shape == "capacitor":
            lines.append(_two_terminal(shape, "C"))
        elif shape.shape == "inductor":
            lines.append(_two_terminal(shape, "L"))
        elif shape.shape == "diode":
            lines.append(_two_terminal(shape, "Do"))
        elif shape.shape == "voltage_source":
            lines.append(_two_terminal(shape, "V"))
        elif shape.shape == "current_source":
            lines.append(_two_terminal(shape, "I"))
        elif shape.shape == "ground":
            lines.append(_ground(shape))
        elif shape.shape == "power":
            lines.append(_power(shape))
        elif shape.shape == "opamp":
            lines.extend(_device_box(shape))
        elif shape.shape == "npn_bjt":
            lines.extend(_device_box(shape))
        elif shape.shape == "pmos":
            lines.extend(_device_box(shape))
        elif shape.shape == "nmos":
            lines.extend(_device_box(shape))
        else:
            lines.extend(_device_box(shape))
    return lines


def _render_circuitikz_wires(geometry: CompiledSchematic) -> list[str]:
    lines: list[str] = []
    for wire in geometry.wires:
        if len(wire.points) < 2:
            continue
        coords = " -- ".join(_pt(point) for point in wire.points)
        lines.append(rf"  \draw {coords};")
    for junction in geometry.junctions:
        lines.append(rf"  \fill {_pt(junction.point)} circle (1.2pt);")
    return lines


def _render_circuitikz_labels(geometry: CompiledSchematic) -> list[str]:
    lines: list[str] = []
    for text in geometry.labels:
        if text.role == "reference" and (text.text.startswith("#PWR") or text.owner_ref.startswith("#SUPPORT")):
            continue
        anchor = text.anchor_position if text.anchor_position is not None else text.position
        label = _latex_escape(text.text)
        lines.append(rf"  \node[font=\scriptsize] at {_pt(anchor)} {{{label}}};")
    return lines


def _render_literal_shape(shape: PlacedShape) -> list[str]:
    left = shape.body_box.left
    top = shape.body_box.top
    right = shape.body_box.right
    bottom = shape.body_box.bottom
    cx = shape.center.x
    cy = shape.center.y
    label = _latex_escape(f"{shape.ref} {shape.value}")
    if shape.shape in {"resistor", "capacitor", "inductor", "diode"}:
        return [
            rf"  \draw ({left:.2f},{top:.2f}) rectangle ({right:.2f},{bottom:.2f});",
            rf"  \node[font=\scriptsize,align=center] at ({cx:.2f},{cy:.2f}) {{{label}}};",
        ]
    if shape.shape in {"voltage_source", "current_source"}:
        radius = max(right - left, bottom - top) / 2
        return [
            rf"  \draw ({cx:.2f},{cy:.2f}) circle ({radius:.2f});",
            rf"  \node[font=\scriptsize,align=center] at ({cx:.2f},{cy:.2f}) {{{label}}};",
        ]
    if shape.shape == "ground":
        return [
            rf"  \draw ({cx:.2f},{top:.2f}) -- ({cx:.2f},{bottom:.2f});",
            rf"  \draw ({cx - 2.00:.2f},{bottom - 1.50:.2f}) -- ({cx + 2.00:.2f},{bottom - 1.50:.2f});",
            rf"  \node[font=\scriptsize] at ({cx:.2f},{bottom + 3.00:.2f}) {{{_latex_escape(shape.ref)}}};",
        ]
    return [
        rf"  \draw ({left:.2f},{top:.2f}) rectangle ({right:.2f},{bottom:.2f});",
        rf"  \node[font=\scriptsize,align=center] at ({cx:.2f},{cy:.2f}) {{{label}}};",
    ]


def _render_literal_text(text: TextPlacement) -> str:
    if text.role == "reference" and text.owner_ref.startswith("#SUPPORT"):
        return ""
    return rf"  \node[font=\scriptsize] at ({text.position.x:.2f},{text.position.y:.2f}) {{{_latex_escape(text.text)}}};"


def _two_terminal(shape: PlacedShape, element: str) -> str:
    a, b = shape.terminals[:2]
    options = [f"l={{{_latex_escape(shape.value)}}}"]
    if not shape.hidden_reference:
        options.append(f"t={{{_latex_escape(shape.ref)}}}")
    return rf"  \draw {_pt(a.point)} to[{element},{','.join(options)}] {_pt(b.point)};"


def _ground(shape: PlacedShape) -> str:
    terminal = shape.terminals[0]
    return rf"  \draw {_pt(terminal.point)} node[ground] {{}};"


def _power(shape: PlacedShape) -> str:
    terminal = shape.terminals[0]
    return rf"  \node[font=\scriptsize,anchor=south] at {_pt(terminal.point)} {{{_latex_escape(shape.value)}}};"


def _device_box(shape: PlacedShape) -> list[str]:
    lines = [
        rf"  \draw ({shape.body_box.left * SCALE:.2f},{-shape.body_box.top * SCALE:.2f}) rectangle ({shape.body_box.right * SCALE:.2f},{-shape.body_box.bottom * SCALE:.2f});",
        rf"  \node[font=\scriptsize,align=center] at {_pt(shape.center)} {{{_latex_escape(shape.ref)}\\{_latex_escape(shape.value)}}};",
    ]
    for terminal in shape.terminals:
        edge = _point_on_box(shape, terminal.point)
        lines.append(rf"  \draw {_pt(terminal.point)} -- {_pt(edge)};")
    return lines


def _reference_section(spec: CircuitSpec) -> str:
    lines = [
        r"\begin{longtable}{p{0.16\linewidth}p{0.18\linewidth}p{0.30\linewidth}p{0.22\linewidth}}",
        r"\textbf{Ref} & \textbf{Kind} & \textbf{Value / Model} & \textbf{Nodes}\\",
        r"\hline",
    ]
    for component in spec.components:
        value = component.model or component.value
        lines.append(
            " & ".join(
                [
                    _latex_escape(component.ref),
                    _latex_escape(component.kind),
                    _latex_escape(value),
                    _latex_escape(", ".join(component.nodes)),
                ]
            )
            + r"\\"
        )
    lines.extend(
        [
            r"\end{longtable}",
            "",
            r"\paragraph{Analyses}",
        ]
    )
    if spec.analyses:
        lines.append(r"\begin{itemize}")
        for analysis in spec.analyses:
            lines.append(rf"  \item \texttt{{{_latex_escape(analysis.command)}}}")
        lines.append(r"\end{itemize}")
    else:
        lines.append("No analyses defined.")
    return "\n".join(lines)


def _starter_notes(spec: CircuitSpec) -> str:
    lines = [
        r"\subsection*{Overview}",
        _latex_escape(_overview_sentence(spec)),
        "",
        r"\subsection*{Operating Notes}",
        r"\begin{itemize}",
    ]
    for sentence in _operating_notes(spec):
        lines.append(r"  \item " + _latex_escape(sentence))
    lines.extend(
        [
            r"\end{itemize}",
            r"\subsection*{Design Notes To Edit}",
            r"\begin{itemize}",
            r"  \item Replace these starter notes with intended operating limits, tuning guidance, and simulation expectations.",
            r"  \item Record any KiCad-specific layout conventions that should stay aligned with the generated schematic.",
            r"  \item Add usage notes for the ngspice analyses that matter for this example.",
            r"\end{itemize}",
        ]
    )
    return "\n".join(lines)


def _overview_sentence(spec: CircuitSpec) -> str:
    kind_names = [_kind_display_name(component.kind) for component in spec.components]
    dominant = ", ".join(kind_names[:3])
    if len(kind_names) > 3:
        dominant += ", and related support parts"
    return f"This generated example captures the {spec.name.replace('_', ' ')} circuit using {dominant}."


def _operating_notes(spec: CircuitSpec) -> list[str]:
    notes = [
        f"Primary simulation commands: {', '.join(analysis.command for analysis in spec.analyses) or 'none specified'}.",
        f"Component count: {len(spec.components)} active entries in the shared CircuitSpec.",
    ]
    named_nodes = sorted({node for component in spec.components for node in component.nodes if node != "0"})
    if named_nodes:
        notes.append(f"Named nets to review during edits: {', '.join(named_nodes[:6])}.")
    if spec.models:
        notes.append(f"Custom device models are embedded for {len(spec.models)} statements.")
    return notes


def _kind_display_name(kind: str) -> str:
    return {
        "V": "voltage sources",
        "I": "current sources",
        "R": "resistors",
        "C": "capacitors",
        "L": "inductors",
        "D": "diodes",
        "Q": "BJTs",
        "X": "subcircuits",
        "M": "MOS devices",
    }.get(kind, kind)


def _pt(point: Point) -> str:
    return f"({point.x * SCALE:.2f},{-point.y * SCALE:.2f})"


def _point_on_box(shape: PlacedShape, point: Point) -> Point:
    x = min(max(point.x, shape.body_box.left), shape.body_box.right)
    y = min(max(point.y, shape.body_box.top), shape.body_box.bottom)
    return Point(x, y)


def _latex_escape(text: str) -> str:
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
    }
    escaped = []
    for char in text:
        escaped.append(replacements.get(char, char))
    return "".join(escaped)
