from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class TexSymbolDefinition:
    name: str
    parameter_count: int
    body_lines: tuple[str, ...]


@dataclass(frozen=True, slots=True)
class TexDrawing:
    environment: str
    options: tuple[str, ...]
    symbol_definitions: tuple[TexSymbolDefinition, ...]
    body_lines: tuple[str, ...]


@dataclass(frozen=True, slots=True)
class TexDocumentSection:
    title: str
    body: str | TexDrawing | None = None
    subsections: tuple["TexDocumentSection", ...] = ()


@dataclass(frozen=True, slots=True)
class TexDocument:
    title: str
    sections: tuple[TexDocumentSection, ...]
    packages: tuple[str, ...]
    author: str = "Generated by mixedsig2cad"
    date_expr: str = r"\today"
    include_table_of_contents: bool = False
