"""High-level mixed-signal spec to KiCad/ngspice generators."""

from .geometry import (
    BoundingBox,
    GeometryNode,
    JunctionPlacement,
    NodeAnchor,
    NodeTrunk,
    PinExitCorridor,
    Point,
    PlacedShape,
    PlacedTerminal,
    SchematicGeometry,
    TerminalRef,
    TerminalTemplate,
    TextPlacement,
    WirePath,
    build_schematic_geometry,
    pack_schematic_geometry,
    validate_schematic_geometry,
)
from .intent import (
    IntentComponent,
    IntentConnection,
    IntentGroup,
    IntentNet,
    IntentPattern,
    SchematicIntent,
    build_schematic_intent,
)
from .layout import build_kicad_layout
from .projections.kicad import (
    KiCadJunctionPlacement,
    KiCadPlacement,
    KiCadProjection,
    KiCadSymbolPlacement,
    KiCadTextPlacement,
    KiCadWireSegment,
    project_geometry_to_kicad,
    validate_kicad_projection,
)
from .spec import Analysis, CircuitSpec, Component
from .topology_layout import (
    TopologyAttachment,
    TopologyConnection,
    TopologyLayout,
    TopologyPlacement,
    TopologyPoint,
    build_topology_layout,
)
from .exporters.kicad import export_kicad_schematic
from .exporters.ngspice import export_ngspice_netlist

__all__ = [
    "Analysis",
    "CircuitSpec",
    "Component",
    "BoundingBox",
    "IntentComponent",
    "IntentConnection",
    "IntentGroup",
    "IntentNet",
    "IntentPattern",
    "GeometryNode",
    "JunctionPlacement",
    "KiCadJunctionPlacement",
    "KiCadPlacement",
    "KiCadProjection",
    "KiCadSymbolPlacement",
    "KiCadTextPlacement",
    "KiCadWireSegment",
    "NodeAnchor",
    "NodeTrunk",
    "PinExitCorridor",
    "PlacedShape",
    "PlacedTerminal",
    "Point",
    "SchematicGeometry",
    "SchematicIntent",
    "TerminalRef",
    "TerminalTemplate",
    "TextPlacement",
    "TopologyAttachment",
    "TopologyConnection",
    "TopologyLayout",
    "TopologyPlacement",
    "TopologyPoint",
    "WirePath",
    "build_kicad_layout",
    "build_schematic_geometry",
    "build_schematic_intent",
    "build_topology_layout",
    "export_kicad_schematic",
    "export_ngspice_netlist",
    "pack_schematic_geometry",
    "project_geometry_to_kicad",
    "validate_kicad_projection",
    "validate_schematic_geometry",
]
